### ISSUE TITLE
Video title not being displayed

### ISSUE THREAD

**Issue by knackrack615** [AcedArmy/Youcord#1]
For some reason the video title is not being displayed.

Everything else is working as expected

Also, i think its a good idea when Youtube is closed or Out of focus for the script not to display anything on discord as another script might want to display something (ex. Plex integration)

Screenshots:
![image](https://user-images.githubusercontent.com/2822335/44825176-077fb980-ac12-11e8-95bc-8c77e7938f97.png)

![image](https://user-images.githubusercontent.com/2822335/44825183-11092180-ac12-11e8-82cf-61a320dac3e6.png)

![image](https://user-images.githubusercontent.com/2822335/44825444-4f531080-ac13-11e8-82aa-df35df56f5fa.png)

**Comment by ghCadia** [comment]
Youtube must of updated their site and changed which element stored it. I fixed this for now but I should automatically check it in the future.

I also made it so Youcord will disconnect from Discord when it detects the socket is not connected to the userscript. And when it detects it again it will reestablish a connection to discord. The reason I did not make it a focus check is since I tend to have youtube running the in background while I do other things.

**Comment by knackrack615** [comment]
You should probably add a variable at the top that the user can change for the focus check.

Most of the time the youtube script overrides my plex script just because i have youtube open in the background without anything playing.

Other than that it works great
